### ISSUE TITLE
Thunderstore installation does not fetch the Discord API DLL

### ISSUE THREAD

**Issue by riking** [Zomatree/Dyson-Sphere-Program-Discord-Rich-Presence#2]
https://dsp.thunderstore.io/package/Zomatree/Discord_RPC/

The Discord DLL is not dropped into the game folder, and the instructions do not render on the store page.

**Comment by Zomatree** [comment]
From what i can tell, there is not way with r2monmanplus to drop the discord sdk into the game files by itself so im going to have to resort to making people manually putting in the sdk into the games, files, i will update the instructions on the store page to do this.
